<%

require 'run_loop'

date = Time.now.strftime('%Y-%m-%d-%H%M-%S')

FileUtils.mkdir("./screenshots") unless File.exists?("./screenshots")
FileUtils.mkdir("./reports") unless File.exists?("./reports")

xamarin_dir = "#{ENV['HOME']}/.xamarin"

devices = {}

device_list = ['pluto', 'neptune', 'venus', 'earp', 'mars', 'pegasi', 'uranus', 'hat', 'denis']

device_list.each do |device|
  dir = "#{xamarin_dir}/devices/#{device}"
  ip = IO.read("#{dir}/ip") if File.exists?("#{dir}/ip")
  udid = IO.read("#{dir}/udid") if File.exists?("#{dir}/udid")
  report = "./reports/#{device}/#{date}-#{device}.html"
  ss_path = "./reports/#{device}/screenshots/"
  ht = {:dir => dir,
        :ip => ip,
        :udid => udid,
        :report => report,
        :ss_path => ss_path}
  devices[device.to_sym] = ht

  FileUtils.mkdir("./reports/#{device}") unless File.exists?("./reports/#{device}")
  FileUtils.mkdir("./reports/#{device}/screenshots") unless File.exists?("./reports/#{device}/screenshots")
end

if ENV["USER"] == "jenkins"
  formatter = "progress"
  formatter = "Slowhandcuke::Formatter"
  keep_sim_open_after = "0"
else
  formatter = "Slowhandcuke::Formatter"
  keep_sim_open_after = "1"
end

default_report = "./reports/calabash-#{date}.html"
ss_path = "./screenshots/"


%>

verbose: CALABASH_FULL_CONSOLE_OUTPUT=1 DEBUG=1
common: -f <%= formatter %> NO_STOP=<%= keep_sim_open_after %> --expand --no-multiline --no-source

ss_path: SCREENSHOT_PATH=<%= ss_path %>

html_report:  -f 'Calabash::Formatters::Html' -o <%= default_report %>
pluto_html:   -f 'Calabash::Formatters::Html' -o <%= devices[:pluto][:report] %>
neptune_html: -f 'Calabash::Formatters::Html' -o <%= devices[:neptune][:report] %>
venus_html:   -f 'Calabash::Formatters::Html' -o <%= devices[:venus][:report] %>
earp_html:    -f 'Calabash::Formatters::Html' -o <%= devices[:earp][:report] %>
mars_html:    -f 'Calabash::Formatters::Html' -o <%= devices[:mars][:report] %>
pegasi_html:    -f 'Calabash::Formatters::Html' -o <%= devices[:pegasi][:report] %>
uranus_html:    -f 'Calabash::Formatters::Html' -o <%= devices[:uranus][:report] %>
denis_html:    -f 'Calabash::Formatters::Html' -o <%= devices[:denis][:report] %>
hat_html:    -f 'Calabash::Formatters::Html' -o <%= devices[:hat][:report] %>

pluto_ss:   SCREENSHOT_PATH=<%= devices[:pluto][:ss_path] %>
neptune_ss: SCREENSHOT_PATH=<%= devices[:neptune][:ss_path] %>
venus_ss:   SCREENSHOT_PATH=<%= devices[:venus][:ss_path] %>
earp_ss:    SCREENSHOT_PATH=<%= devices[:earp][:ss_path] %>
mars_ss:    SCREENSHOT_PATH=<%= devices[:mars][:ss_path] %>
pegasi_ss:    SCREENSHOT_PATH=<%= devices[:pegasi][:ss_path] %>
uranus_ss:    SCREENSHOT_PATH=<%= devices[:uranus][:ss_path] %>
denis_ss:    SCREENSHOT_PATH=<%= devices[:denis][:ss_path] %>
hat_ss:    SCREENSHOT_PATH=<%= devices[:hat][:ss_path] %>

no_launch:    NO_LAUNCH=1 --tags ~@launch
do_launch:    NO_LAUNCH=0 --tags ~@no_launch
no_reset_btw: RESET_BETWEEN_SCENARIOS=0
reset_btw:    RESET_BETWEEN_SCENARIOS=1

ipad_tags:   -p common --tags ~@iphone --tags ~@iphone_only
iphone_tags: -p common --tags ~@ipad   --tags ~@ipad_only

simulator:     -p common -p ss_path -p html_report --tags ~@device_only --tags ~@device
sim_launch:    -p simulator -p do_launch -p no_reset_btw
sim_no_launch: -p simulator -p no_launch -p no_reset_btw

default:            -p sim_launch -p iphone_tags

no_uia:   -p common -p ss_path -p html_report -p no_launch -p no_reset_btw -p sim61_4in

# required only for devices
bundle_id:    BUNDLE_ID=com.littlejoysoftware.Briar-cal

device_common:  -p bundle_id --tags ~@simulator --tags ~@simulator_only

pluto_common:   DEVICE_TARGET=<%= devices[:pluto][:udid] %>   DEVICE_ENDPOINT=<%= devices[:pluto][:ip] %> -p device_common -p ipad_tags   -p pluto_html     -p pluto_ss
# cannot test collection views on iOS 5
pluto:          -p pluto_common -p no_launch --tags ~@collection_view

neptune_common: DEVICE_TARGET=<%= devices[:neptune][:udid] %> DEVICE_ENDPOINT=<%= devices[:neptune][:ip] %> -p device_common -p iphone_tags -p neptune_html -p neptune_ss

# cannot test email views without launching on iOS 6
neptune:        -p neptune_common -p no_launch --tags ~@email
neptune_launch: -p neptune_common -p do_launch

venus_common:   DEVICE_TARGET=<%= devices[:venus][:udid] %>   DEVICE_ENDPOINT=<%= devices[:venus][:ip] %> -p device_common -p ipad_tags -p venus_html     -p venus_ss
venus:          -p venus_common -p do_launch

mars_common:   DEVICE_TARGET=<%= devices[:mars][:udid] %> DEVICE_ENDPOINT=<%= devices[:mars][:ip] %> -p device_common  -p ipad_tags  -p mars_html -p mars_ss
mars:          -p mars_common -p do_launch

uranus_common: DEVICE_TARGET=<%= devices[:uranus][:udid] %> DEVICE_ENDPOINT=<%= devices[:uranus][:ip] %> -p device_common  -p iphone_tags   -p uranus_html -p uranus_ss
uranus:        -p uranus_common -p do_launch

pegasi_common: DEVICE_TARGET=<%= devices[:pegasi][:udid] %> DEVICE_ENDPOINT=<%= devices[:pegasi][:ip] %> -p device_common  -p ipad_tags  -p pegasi_html  -p pegasi_ss
pegasi:        -p pegasi_common -p do_launch

hat:    DEVICE_TARGET=<%= devices[:hat][:udid] %>   DEVICE_ENDPOINT=<%= devices[:hat][:ip] %>   -p device_common  -p iphone_tags -p do_launch -p hat_html -p hat_ss
denis:  DEVICE_TARGET=<%= devices[:denis][:udid] %> DEVICE_ENDPOINT=<%= devices[:denis][:ip] %> -p device_common  -p iphone_tags -p do_launch -p denis_html -p denis_ss
