# careful using the @not_xtc tag
# use for stuff like Scenario Outlines which are nyi on XTC
not_xtc:     --tags ~@not_xtc
not_sim:     --tags ~@simulator --tags ~@simulator_only
no_launch:   --tags ~@no_launch
iphone_only: --tags ~@ipad --tags ~@ipad_only
ipad_only:   --tags ~@iphone --tags ~@iphone_only

args:         --expand --backtrace --no-multiline
tags:        -p not_xtc -p not_sim -p no_launch

default:     -p tags -p args

wip:         -p tags --tags @wip
flicker:     -p tags --tags @flickering
iphone:      -p tags -p iphone_only
ipad:        -p tags -p ipad_only
xtc_wip:     -p tags --tags @xtc_wip

# page model
page:        -p tags --tags @page

### issues/pull requests

# keyboard delete
issue_256:   -p tags --tags @issue_256
# escaping 'backslash' for uia_type_string
issue_284:   -p tags --tags @issue_284
keyboard:    -p tags --tags @keyboard

# deprecated Device::iphone_5? and added Device::iphone_4in
issue_319:   -p tags --tags @issue_319


collections: -p tags --tags @collection_view
keychain:    -p tags --tags @issue_323
