source 'https://rubygems.org'
#gem 'briar', '0.0.7'
# bundle config local.GEM_NAME /path/to/local/git/repository
#gem 'briar', '0.0.9'
gem 'briar', :github => 'jmoody/briar', :branch => '0.0.9'
#gem 'briar', :github => 'jmoody/briar', :branch => 'master'

#gem 'calabash-cucumber', :github => 'jmoody/calabash-ios', :branch => '0.9.x'
#gem 'calabash-cucumber', :github => 'jmoody/calabash-ios', :branch => '0.9.x-riseup-branch'
gem 'calabash-cucumber', :github => 'jmoody/calabash-ios', :branch => '0.9.x-datepicker-change-date-operation'


