source 'https://rubygems.org'

if `whoami`.strip.eql? 'moody'

  # i use bundle and bundle config to specify local gem locations
  # bundle config local.GEM_NAME /path/to/local/git/repository

  gem 'briar', :github => 'jmoody/briar', :branch => '0.1.0'

  #gem 'calabash-cucumber', :github => 'jmoody/calabash-ios', :branch => '0.9.x'
  gem 'calabash-cucumber', :github => 'jmoody/calabash-ios', :branch => '0.9.x-add-slider-operation'

else
  gem 'briar', '0.0.9'
end




