task :show_simulator do
  sh "/usr/bin/osascript -e 'tell application \"#{ENV['DEVELOPER_DIR']}/Platforms/iPhoneSimulator.platform/Developer/Applications/iPhone Simulator.app\" to activate'"
  sh "/usr/bin/osascript -e 'tell application \"RubyMine\" to activate'"
end

task :kill_instruments do
  system('killall -9 instruments')
  #system('killall -9 installd')
end
