require 'irb'

task :activate_simulator do
  sh "/usr/bin/osascript -e 'tell application \"#{ENV['DEVELOPER_DIR']}/Platforms/iPhoneSimulator.platform/Developer/Applications/iPhone Simulator.app\" to activate'"
end

task :show_simulator do
  Rake::Task['activate_simulator'].invoke
  sh "/usr/bin/osascript -e 'tell application \"RubyMine\" to activate'"
end

task :xamarin do
  sh 'xamarin-build.sh'
end

task :xamarin do
  system('xamarin-upload-example.sh')
end

task :tag_report do
  sh 'cucumber -d -f Cucumber::Formatter::ListTags'
end

def bundle_id
  'com.littlejoysoftware.Briar-cal'
end

def read_device_info (device, kind)
  kind = kind.to_sym
  kinds = [:ip, :udid, :serial]
  unless kinds.include?(kind)
    raise "#{kind} must be one of '#{kinds}'"
  end
  cmd = "cat ~/.xamarin/devices/#{device}/#{kind} | tr -d '\n'"
  `#{cmd}`
end

# controls the launching of the simulator
# iOS 5 is no longer supported in Instruments
def sdk_versions
  {:ios6 => '6.1',
   :ios7 => '7.0'}
end


def default_device_opts
  bundle_path = `which bundle`
  use_bundler = (not bundle_path.eql?(''))
  {:bundle =>  use_bundler,
  :sdk_version => sdk_versions[:ios7] }
end

def ios_console_cmd(device, opts={})
  default_opts = default_device_opts()
  opts = default_opts.merge(opts)

  # make a screenshot directory if one does not exist
  # *** trailing slash required ***
  ss_path = './screenshots/'
  FileUtils.mkdir(ss_path) unless File.exists?(ss_path)

  env = ["SCREENSHOT_PATH=#{ss_path}",
         'DEBUG=1',
         'CALABASH_FULL_CONSOLE_OUTPUT=1']

  if device.eql? :simulator
    udid = 'simulator'
    env << "DEVICE_TARGET='#{udid}'"
    sdk_version = opts[:sdk_version]
    env << "SDK_VERSION='#{sdk_version}'"
  else
    udid = read_device_info device, :udid
    env << "DEVICE_TARGET='#{udid}'"
    ip = read_device_info device, :ip
    env << "DEVICE_ENDPOINT='#{ip}'"
    bundle_id = bundle_id()
    env << "BUNDLE_ID='#{bundle_id}'"
  end

  env << "IRBRC='./.irbrc'"
  env << 'bundle exec' if opts[:bundle]
  env << 'irb'
  env.join(' ')
end


def ios_irb (device, opts={})
  default_opts = default_device_opts()
  opts = default_opts.merge(opts)
  exec "#{ios_console_cmd(device, opts)}"
end

# calabash simulator consoles

task :sim6 do ios_irb(:simulator, {:sdk_version => sdk_versions[:ios6]}) end
task :sim7 do ios_irb(:simulator, {:sdk_version => sdk_versions[:ios7]}) end

namespace :moody do

  # calabash device consoles
  task :venus do ios_irb('venus') end
  task :neptune do ios_irb('neptune') end
  task :earp do ios_irb('earp') end
  task :pluto do ios_irb('pluto') end

  #noinspection RubyUnusedLocalVariable
  task :deploy, :device do |t, args|
    sh './xamarin-build.sh'
    device = args.device
    udid_cmd = "cat ~/.xamarin/devices/#{device}/udid | tr -d '\n'"
    udid = `#{udid_cmd}`
    bundle='./xamarin/Briar-cal.app'
    sh "~/bin/ios-deploy --id #{udid} --bundle #{bundle}"
  end

  #noinspection RubyUnusedLocalVariable
  task :remove, :device do |t, args|
    device = args.device
    udid_cmd = "cat ~/.xamarin/devices/#{device}/udid | tr -d '\n'"
    udid = `#{udid_cmd}`
    bundle_id = bundle_id()
    bin_dir='~/bin/libimobiledevice'
    sh "export DYLD_LIBRARY_PATH=#{bin_dir}; #{bin_dir}/ideviceinstaller -U #{udid} --uninstall #{bundle_id}"
  end

  #noinspection RubyUnusedLocalVariable
  task :reinstall, :device do |t, args|
    device = args.device
    Rake::Task['moody:remove'].invoke(device)
    Rake::Task['moody:deploy'].invoke(device)
  end

  task :venus_reinstall do Rake::Task['moody:reinstall'].invoke('venus') end
  task :neptune_reinstall do Rake::Task['moody:reinstall'].invoke('neptune') end
  task :earp_reinstall do Rake::Task['moody:reinstall'].invoke('earp') end

  # test cloud
  #noinspection RubyUnusedLocalVariable
  task :tc, :device_set, :profile do |t, args|
    sh './xamarin-build.sh'

    api_key= `cat ~/.xamarin/test-cloud/moody | tr -d '\n'`

    device_set = args.device_set
    device_set = 'fdc46092' if device_set.eql?('iphones')

    profile = args.profile
    profile = 'xtc_wip' if profile.eql?('wip')

    ipa = 'RiseUp-cal.ipa'
    # this will not work like you expect it to
    #sh 'cd xamarin; bundle update'
    sh "cd xamarin; bundle exec test-cloud submit #{ipa} #{api_key} -d #{device_set} --config cucumber.yml --profile #{profile}"
  end

end

